select * from [HDHI Admission data]

-- Steps to clean Date using Database;
------------------------------------------
-- 1) Find Duplicate Records in the table;
------------------------------------------
-- Creating a CTE(Temporary Table) called 'CleanData', to extract non-duplicate date.
WITH CleanData AS
(
-- Selecting all the data to identify duplicate using 'Dup_No' Column generated by window function 'ROW_NUMBER()' to identify duplicate records. 
SELECT * ,
ROW_NUMBER() OVER(PARTITION BY MRD_No, D_O_A, D_O_D ORDER BY MRD_No) AS Dup_NO
FROM [AutoCare DB].[dbo].[HDHI Admission data]
-- ORDER BY MRD_No;
)

-- selecting non-duplicate data
SELECT * from CleanData
WHERE Dup_NO = 1 AND MRD_No is NOT NULL

-----------------------------------------------------------------------------------------------------------------

-- Create view to store the cleaned data for future use
CREATE OR ALTER VIEW HospitalAdmission_VW AS
WITH CleanData AS
(

SELECT * ,
ROW_NUMBER() OVER(PARTITION BY MRD_No, D_O_A, D_O_D ORDER BY MRD_No) AS Dup_NO
FROM [AutoCare DB].[dbo].[HDHI Admission data]
-- ORDER BY MRD_No;
)

SELECT * from CleanData
WHERE Dup_NO = 1 AND MRD_No is NOT NULL
--ORDER BY MRD_No;


